### ISSUE TITLE
Push to npm?

### ISSUE THREAD

**Issue by Pancia** [HenrikJoreteg/semi-static#3]
Hey Henrik,

I've never published to npm before, but I'm assuming it's something that only you are setup to do?
If you could check out the few changes I've made and push if it looks good?

**Comment by HenrikJoreteg** [comment]
What's your npm username? I'll give you perms there too

**Comment by HenrikJoreteg** [comment]
It's super easy, just create an account on npm. You can do just do `npm login` I think

**Comment by Pancia** [comment]
pancia

EDIT: didnt mean to close lol

**Comment by HenrikJoreteg** [comment]
ok, i've added you as an owner on npm for this package, you can use `npm version` to bump the version number as well. 

In this case, in order to follow semver, this should really be published as `1.0.0`.

I use these scripts to make it easy: http://ampersandjs.com/learn/bug-triage-process#publishing

That will also push a git tag with the same version to github.

**Comment by HenrikJoreteg** [comment]
To clarify the reason it should be 1.0.0 is because there's special rules for `0.x.x` version ranges (it's considered experimental) per http://semver.org/.

**Comment by Pancia** [comment]
Done! https://www.npmjs.com/package/semi-static

**Comment by HenrikJoreteg** [comment]
Cool, nice work!
